dist: xenial
language: python
python:
  - "3.6"
cache:
  directories:
    - eggs
    - $HOME/.local
#sudo: false
install:
# - deactivate
# - pip install --user psycopg2
  - pip install -U psycopg2 setuptools
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
after_success:
  - bin/coveralls
