language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - python-psycopg2
cache:
  directories:
   - eggs
sudo: false
install:
  - deactivate
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
