# Generated by Django 4.2.13 on 2024-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lizard_auth_client", "0007_auto_20181116_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
